=== patrick-jennewein/UMSL_Course_Scheduler/app/xml/course_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CSBSReq" type="CSBSReqType">
    <xs:annotation>
      <xs:documentation>
	There are 3 sets of classes that are included in this file:
		All Computer Science courses &lt; 5000 (Core Courses and Electives)
		Math courses - only those required for the BS in CS (no other Math courses are included)
		English course - only one required for the BS in CS (no other English courses are included)

	This file started with data from the following files:
		BSCSDegreeReq.xml (provided by Janikow)
		Rotation.xml (provided by Janikow)
		Courses2016.xml (provided by Janikow)

	Requirements are provided by Course Dependencies Flyer on the UMSL CS website
		https://www.umsl.edu/cmpsci/undergraduate-studies/BS-cs.html

	Rotation terms were provided by the Undergraduate Course Rotation Document
		https://www.umsl.edu/cmpsci/undergraduate-studies/3yearcourse.html
		From comparing the Rotations on this document to myView, some of the rotations
		do not seem to be updated.

	Rotation terms for Math/English courses were provided by the Course Dependencies Flyer
		on the UMSL CS website
		https://www.umsl.edu/cmpsci/undergraduate-studies/BS-cs.html
</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="rotation_termType">
    <xs:sequence>
      <xs:element name="term">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Spring"/>
            <xs:enumeration value="Fall"/>
            <xs:enumeration value="Summer"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="time_code"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="courseType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="subject">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CMP SCI"/>
            <xs:enumeration value="MATH"/>
            <xs:enumeration value="ENGLISH"/>
            <xs:enumeration value="INTDSC"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="course_number"/>
      <xs:element type="xs:string" name="course_name"/>
      <xs:element name="credit">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="1-3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="rotation_termType" name="rotation_term"/>
      <xs:element type="xs:string" name="course_description"/>
      <xs:element type="xs:string" name="prerequisite_description"/>
      <xs:element type="prerequisiteType" name="prerequisite"/>
      <xs:element type="xs:string" name="concurrent"/>
      <xs:element type="xs:string" name="paired"/>
      <xs:element type="xs:boolean" name="required"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="or_choiceType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="and_required" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="prerequisiteType">
    <xs:sequence>
      <xs:element type="or_choiceType" name="or_choice" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="xs:string" name="additional_preq" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CoreCoursesType">
    <xs:sequence>
      <xs:element type="courseType" name="course" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ElectivesType">
    <xs:sequence>
      <xs:element type="courseType" name="course" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MathandStatisticsType">
    <xs:sequence>
      <xs:element type="courseType" name="course" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OtherCoursesType">
    <xs:sequence>
      <xs:element type="courseType" name="course" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CSBSReqType">
    <xs:sequence>
      <xs:element type="CoreCoursesType" name="CoreCourses"/>
      <xs:element type="ElectivesType" name="Electives"/>
      <xs:element type="MathandStatisticsType" name="MathandStatistics"/>
      <xs:element type="OtherCoursesType" name="OtherCourses"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== patrick-jennewein/UMSL_Course_Scheduler/app/xml/course_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	There are 3 sets of classes that are included in this file:
		All Computer Science courses < 5000 (Core Courses and Electives)
		Math courses - only those required for the BS in CS (no other Math courses are included)
		English course - only one required for the BS in CS (no other English courses are included)

	This file started with data from the following files:
		BSCSDegreeReq.xml (provided by Janikow)
		Rotation.xml (provided by Janikow)
		Courses2016.xml (provided by Janikow)

	Requirements are provided by Course Dependencies Flyer on the UMSL CS website
		https://www.umsl.edu/cmpsci/undergraduate-studies/BS-cs.html

	Rotation terms were provided by the Undergraduate Course Rotation Document
		https://www.umsl.edu/cmpsci/undergraduate-studies/3yearcourse.html
		From comparing the Rotations on this document to myView, some of the rotations
		do not seem to be updated.

	Rotation terms for Math/English courses were provided by the Course Dependencies Flyer
		on the UMSL CS website
		https://www.umsl.edu/cmpsci/undergraduate-studies/BS-cs.html
-->
<CSBSReq
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="course_data.xsd">
	<CoreCourses>
		<course>
			<subject>CMP SCI</subject>
			<course_number>1000</course_number>
			<course_name>Computer Science Experiences</course_name>
			<credit>1</credit>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>E</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<course_description>This course is for recently declared undergraduate students majoring in Computer Science or Computing Technology. Topics may include resources that are available on campus and in the department, career opportunities, choosing the right degree, and exploration of concepts, skills and practices that are essential for successful careers. This course should be taken by freshmen and transfers within the first two semesters of declaring the major.</course_description>
            <prerequisite_description>No prerequisites. </prerequisite_description>
			<required>true</required>
        </course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>1250</course_number>
			<course_name>Introduction to Computing</course_name>
			<credit>3</credit>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<course_description>Provides an introduction to the concepts of computation, problem solving, and computer systems, Covers fundamental programming constructs, basic data types, and modularization using a modern high level language. Problem solving skills are developed through a progression of programming projects.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>MATH 1030</and_required>
				</or_choice>
				<or_choice>
					<and_required>MATH 1045</and_required>
				</or_choice>
				<or_choice>
					<and_required>MATH 1100</and_required>
				</or_choice>
				<or_choice>
					<and_required>MATH 1800</and_required>
				</or_choice>
				<or_choice>
					<and_required>Proctored ALEKS Score</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisites: MATH 1030 with a B- or better, or MATH 1045 with B- or better, or MATH 1100 (can be taken concurrently), or MATH 1800 (can be taken concurrently), or a 70% on the proctored UMSL Math Placement obtained at most one year prior to enrollment in this course. </prerequisite_description>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>2250</course_number>
			<course_name>Programming and Data Structures</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<credit>3</credit>
			<course_description>A continuation of CMP SCI 1250. Discusses properties and implementation of abstract data types such as lists, trees, stacks and queues. Introduces procedural and class abstraction, basic program architecture, use of interfaces, modular programming, and file processing.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>CMP SCI 1250</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisite: CMP SCI 1250. </prerequisite_description>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>2261</course_number>
			<course_name>Object-Oriented Programming</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<credit>3</credit>
			<course_description>Introduces object-oriented concepts, terminology, and notation (UML) using Java. Covers encapsulation, classes, objects, inheritance, and the use of class libraries. Additional topics may include graphical user interfaces, applets, and related tools and technologies.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>CMP SCI 2250</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisites: CMP SCI 2250 (may be taken concurrently). </prerequisite_description>
			<concurrent>
				CMP SCI 2250
			</concurrent>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>2700</course_number>
			<course_name>Computer Organization and Architecture</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<credit>3</credit>
			<course_description>Introduces details of computer systems from architectural and organizational points of view. Covers data representation, basic digital logic circuits, memory types and hierarchies, I/O and storage devices, CPU architectures such as RISC, CISC, parallel, and multi-core.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>CMP SCI 2250</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisites: CMP SCI 2250 (can be taken concurrently). </prerequisite_description>
			<concurrent>
				CMP SCI 2250
			</concurrent>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>2750</course_number>
			<course_name>Linux Environment and Programming</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<credit>3</credit>
			<course_description>Covers systems programming, scripting, libraries, utilities, and development tools. Additional programming topics include piping, binary files, exception handling, command-line arguments and symbolic debugging. This course also explores tools available in the Unix/Linus environments.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>CMP SCI 2250</and_required>
					<and_required>CMP SCI 2700</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisites: CMP SCI 2250 and CMP SCI 2700 (CMP SCI 2700 can be taken concurrently). </prerequisite_description>
			<concurrent>
				CMP SCI 2700
			</concurrent>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>3010</course_number>
			<course_name>Web Programming</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O</time_code>
			</rotation_term>
			<credit>3</credit>
			<course_description>Provides a survey of current Web technologies including markup languages (such as HTML/XHTML, CSS, XML), client side languages (such as JavaScript), server side languages (such as PERL, PHP), and Web protocols. This course requires client-server computing projects.</course_description>
			<prerequisite>
				<or_choice>
					<and_required>CMP SCI 2250</and_required>
				</or_choice>
			</prerequisite>
            <prerequisite_description>Prerequisites: CMP SCI 2250 (can be taken concurrently) or students with familiarity with basic data structures may enroll with consent of instructor. </prerequisite_description>
			<concurrent>
				CMP SCI 2250
			</concurrent>
			<required>true</required>
		</course>
		<course>
			<subject>CMP SCI</subject>
			<course_number>3130</course_number>
			<course_name>Design and Analysis of Algorithms</course_name>
			<rotation_term>
				<term>Spring</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Fall</term>
				<time_code>D, E, O</time_code>
			</rotation_term>
			<rotation_term>
				<term>Summer</term>
				<time_code>O, H</time_code>
			</rotation_term>
			<credit>3</credit>
