=== patrick-jennewein/UMSL_Course_Scheduler/app/xml/cscertificate_schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--these are the only subjects in the CS degree-->
    <xs:simpleType name="SubjectList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CMP SCI"/>
            <xs:enumeration value="MATH"/>
            <xs:enumeration value="ENGLISH"/>
            <xs:enumeration value="INFSYS"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Credit hours are usually single integers, but a couple courses have variable list of credit hours-->
    <xs:simpleType name="CreditHoursRange">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-5]( ?[1-5])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RotationTerms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Spring"/>
            <xs:enumeration value="Fall"/>
            <xs:enumeration value="Summer"/>
            <xs:enumeration value=""/>
            <!--Should not have empty value here, but some rotation data is missing. this is a temp fix-->
        </xs:restriction>
    </xs:simpleType>

    <!--Includes all possible timecodes. Add explanation above-->
    <xs:simpleType name="RotationTimeCodes">
        <xs:restriction base="xs:string">
            <xs:pattern value="(A|D|E|H|O|)(, (A|D|E|H|O))*"/>
            <!--List cannot be nillable, so empty choice added-->
        </xs:restriction>
    </xs:simpleType>

    <!--Defines groups of prerequisites for each "or_choice" grouping.-->
    <xs:complexType name="PrerequisiteGroup">
        <xs:sequence>
            <xs:element name="and_required" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:list itemType="xs:string"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!--Defines order for the descriptive elements of required courses and elective courses. Element sequence is the same for both, but elective courses have fewer required elements since only "subject", "course_number", "course_name", and "credit" are used in map generation-->
    <xs:complexType name="RequiredCourseDetails">
        <xs:sequence>
            <xs:element name="subject" type="SubjectList"/>
            <xs:element name="course_number" type="xs:integer"/>
            <xs:element name="course_name" type="xs:string"/>
            <xs:element name="credit" type="CreditHoursRange"/>
            <xs:element name="rotation_term" maxOccurs="3" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="term" type="RotationTerms"/>
                        <xs:element name="time_code" type="RotationTimeCodes" nillable="true"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="course_description" type="xs:string"/>
            <xs:element name="prerequisite_description" type="xs:string"/>
            <xs:element name="prerequisite" minOccurs="0" form="qualified">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="or_choice" type="PrerequisiteGroup" maxOccurs="unbounded" minOccurs="0"/>
                        <xs:element name="additional_preq" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="paired" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:list itemType="xs:string"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ElectiveCourseDetails">
        <xs:sequence>
            <xs:element name="subject" type="SubjectList"/>
            <xs:element name="course_number" type="xs:integer"/>
            <xs:element name="course_name" type="xs:string"/>
            <xs:element name="credit" type="CreditHoursRange"/>
            <xs:element name="rotation_term" maxOccurs="3" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="term" type="RotationTerms"/>
                        <xs:element name="time_code" type="RotationTimeCodes" nillable="true"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="course_description" type="xs:string"/>
            <xs:element name="prerequisite" minOccurs="0" form="qualified">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="or_choice" type="PrerequisiteGroup" maxOccurs="unbounded" minOccurs="0"/>
                        <xs:element name="additional_preq" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="paired" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:list itemType="xs:string"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="NoOfElectives">
        <xs:sequence>
            <xs:element name="num" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="NoOfElectives" type="NoOfElectives"/>

    <xs:complexType name="CertCourses">
        <xs:sequence>
            <xs:element name="CertCore">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="course" type="RequiredCourseDetails" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="CertElectives">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="course" type="ElectiveCourseDetails" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="NoOfElectives" type="NoOfElectives"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="CSCertificates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AICERTReq" type="CertCourses"/>
                <xs:element name="CYBERCERTReq" type="CertCourses"/>
                <xs:element name="DATACERTReq" type="CertCourses"/>
                <xs:element name="MOBILECERTReq" type="CertCourses"/>
                <xs:element name="WEBCERTReq" type="CertCourses"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== patrick-jennewein/UMSL_Course_Scheduler/app/xml/cscertificate_data.xml
<?xml version="1.0" encoding="UTF-8"?>

<CSCertificates xsi:noNamespaceSchemaLocation="./cscertificate_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <AICERTReq>
        <CertCore>
            <course>
                <subject>CMP SCI</subject>
                <course_number>3130</course_number>
                <course_name>Design and Analysis of Algorithms</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Spring</term>
                    <time_code>D, E, O</time_code>
                </rotation_term>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>D, E, O</time_code>
                </rotation_term>
                <rotation_term>
                    <term>Summer</term>
                    <time_code>O, H</time_code>
                </rotation_term>
                <course_description>Addresses the design and analysis of fundamental algorithms in computer science. Studies basic sorting algorithms priority queues, order statistics, search trees, and hash tables. Analysis techniques may involve time and space complexity analysis of both iterative and recursive algorithms, analysis of algorithm correctness, and amortized complexity analysis. Additional topics may include data compression, string manipulation, greedy algorithms, dynamic programming, and graph traversal.</course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 2250</and_required>
                        <and_required>MATH 1320</and_required>
                        <and_required>MATH 3000</and_required>
                    </or_choice>
                </prerequisite>
                <prerequisite_description>Prerequisites: CMP SCI 2250, MATH 1320, and MATH 3000. </prerequisite_description>
                <required>true</required>
            </course>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4300</course_number>
                <course_name>Introduction to Artificial Intelligence</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Spring</term>
                    <time_code>H</time_code>
                </rotation_term>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>H</time_code>
                </rotation_term>
                <course_description>This course provides an introduction to artificial intelligence. The list of topics may include search, planning, knowledge-based reasoning, probabilistic inference, machine learning, natural language processing, and practical applications. Credit cannot be granted for both CMP SCI 4300 and CMP SCI 5300.</course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 3130</and_required>
                    </or_choice>
                </prerequisite>
                <prerequisite_description>The list of topics may include search, planning, knowledge-based reasoning, probabilistic inference, machine learning, natural language processing, and practical applications. Credit cannot be granted for both CMP SCI 4300 and CMP SCI 5300.</prerequisite_description>
                <paired>CMP SCI 5300</paired>
                <required>true</required>
            </course>
        </CertCore>
        <CertElectives>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4151</course_number>
                <course_name>Introduction to Statistical Methods for Data Science</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>H</time_code>
                </rotation_term>
                <course_description>This course covers statistical inference with emphasis on applications and computer simulation. Topics may include multivariate distributions, transformations and combinations of random variables, sampling distributions, maximum likelihood, bootstrap, order statistics, hypothesis testing, likelihood ratio tests, Monte Carlo methods, Bayesian inference, and sufficient statistics. </course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 1250</and_required>
                        <and_required>MATH 1900</and_required>
                        <and_required>MATH 1320</and_required>
                    </or_choice>
                </prerequisite>
                <prerequisite_description>Prerequisites: CMP SCI 1250, MATH 1900, and an introductory statistics course (ANTHRO 3220/SOC 3220, BIOL 4122, CRIMIN 2220, ECON 3100, MATH 1320, POL SCI 3000, or PSYCH 2201). </prerequisite_description>
            </course>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4320</course_number>
                <course_name>Introduction to Evolutionary Computation</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Spring</term>
                    <time_code>H</time_code>
                </rotation_term>
                <course_description>This course introduces the concepts of nature-inspired problem solving with artificial evolution using selection, crossover, mutation and inheritance. It discusses applications of evolutionary algorithms, overviews the existing models and instances, and analyzes specific instances such as genetic algorithms, evolutionary programming, evolution strategies, and genetic programming. </course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 2261</and_required>
                        <and_required>CMP SCI 2750</and_required>
                        <and_required>CMP SCI 3130</and_required>
                    </or_choice>
                </prerequisite>
                <prerequisite_description>Prerequisites: CMP SCI 2261, CMP SCI 2750 and CMP SCI 3130. </prerequisite_description>
            </course>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4340</course_number>
                <course_name>Introduction to Machine Learning</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Spring</term>
                    <time_code>H</time_code>
                </rotation_term>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>H</time_code>
                </rotation_term>
                <course_description>Provides an introduction to machine learning in the context of applications such as data mining, natural language processing, and adaptive computer systems. The course reviews several supervised, unsupervised, and reinforcement machine learning techniques such as naive Bayes networks, clustering, and decision trees. Selected concepts in computational learning theory may also be covered. Credit cannot be granted for both CMP SCI 4340 and CMP SCI 5340.</course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 4342</and_required>
                    </or_choice>
                    <or_choice>
                        <and_required>CMP SCI 2261</and_required>
                        <and_required>CMP SCI 3130</and_required>
                    </or_choice>
                </prerequisite>
                <paired>CMP SCI 5340</paired>
                <prerequisite_description>Prerequisites: CMP SCI 4342, or CMP SCI 2261 and CMP SCI 3130, or consent of instructor.</prerequisite_description>
            </course>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4342</course_number>
                <course_name>Introduction to Data Mining</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Spring</term>
                    <time_code>H</time_code>
                </rotation_term>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>H</time_code>
                </rotation_term>
                <course_description>This course provides an introduction to data mining principles, algorithms and applications. Topics may include data preprocessing, data transformation, similarity and dissimilarity measures, data representation, classification techniques, association analysis, cluster analysis, regression, dimension reduction, and anomaly detection. Credit not granted for both CMP SCI 4342 and CMP SCI 5342.</course_description>
                <prerequisite>
                    <or_choice>
                        <and_required>CMP SCI 2261</and_required>
                        <and_required>CMP SCI 3130</and_required>
                    </or_choice>
                    <or_choice>
                        <and_required>CMP SCI 4200</and_required>
                    </or_choice>
                </prerequisite>
                <paired>CMP SCI 5342</paired>
                <prerequisite_description>Prerequisites: CMP SCI 2261 and CMP SCI 3130, or CMP SCI 4200, or consent of the instructor. </prerequisite_description>
            </course>
            <course>
                <subject>CMP SCI</subject>
                <course_number>4370</course_number>
                <course_name>Introduction to Biological Data Science</course_name>
                <credit>3</credit>
                <rotation_term>
                    <term>Fall</term>
                    <time_code>E</time_code>
                </rotation_term>
